//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [DbConfigurationType(typeof(MySql.Data.EntityFramework.MySqlEFConfiguration))]
    public partial class OralCMSDBEntities : DbContext
    {
        public OralCMSDBEntities()
            : base("name=OralCMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<keyword> keywords { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<subsery> subseries { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<transcription> transcriptions { get; set; }
    }
}
