//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsery
    {
        public int Id { get; set; }
        public short CollectionId { get; set; }
        public string SubseriesName { get; set; }

        public string Number { get; set; }
        public string Dates { get; set; }
        public string Note { get; set; }
        public string Subjects { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string ScopeAndContent { get; set; }
        public string CustodialHistory { get; set; }
        public string Size { get; set; }
        public string Acquisitioninfo { get; set; }
        public string Language { get; set; }
        public string PreservationNote { get; set; }
        public string Rights { get; set; }
        public string AccessRestrictions { get; set; }
        public string PublicationRights { get; set; }
        public string PreferredCitation { get; set; }
        public string RelatedCollection { get; set; }
        public string SeparatedMaterial { get; set; }
        public string OriginalLocation { get; set; }
        public string CopiesLocation { get; set; }
        public string PublicationNote { get; set; }
        public string Creator { get; set; }
        public string Contributors { get; set; }
        public string ProcessedBy { get; set; }
        public string Sponsors { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
