//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class transcription
    {
        public int Id { get; set; }
        public string ProjectCode { get; set; }
        public bool IsPriority { get; set; }
        public string ReasonForPriority { get; set; }
        public string InitialNote { get; set; }
        public short CollectionId { get; set; }
        public int SubseriesId { get; set; }
        public string Interviewee { get; set; }
        public string Interviewer { get; set; }
        public string InterviewDate { get; set; }
        public string InterviewDate1 { get; set; }
        public string InterviewDate2 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string Subject { get; set; }
        public string ScopeAndContents { get; set; }
        public string Format { get; set; }
        public string Type { get; set; }
        public string Publisher { get; set; }
        public string RelationIsPartOf { get; set; }
        public string CoverageSpatial { get; set; }
        public string CoverageTemporal { get; set; }
        public string Rights { get; set; }
        public string Language { get; set; }
        public string Identifier { get; set; }
        public string Transcript { get; set; }
        public string FileName { get; set; }
        public bool IsOnline { get; set; }
        public bool IsRosetta { get; set; }
        public bool IsRosettaForm { get; set; }
        public bool IsRestriction { get; set; }
        public bool IsDarkArchive { get; set; }
        public string RestrictionNote { get; set; }
        public string DarkArchiveNote { get; set; }
        public string AudioEquipmentUsed { get; set; }
        public string VideoEquipmentUsed { get; set; }
        public string InterviewerNote { get; set; }
        public string GeneralNote { get; set; }
        public bool ReleaseForm { get; set; }
        public string Place { get; set; }
        public string TranscriberAssigned { get; set; }
        public string AuditCheckCompleted { get; set; }
        public string FirstEditCompleted { get; set; }
        public string SecondEditCompleted { get; set; }
        public string ThirdEditCompleted { get; set; }
        public Nullable<System.DateTime> DraftSentDate { get; set; }
        public string EditWithCorrectionCompleted { get; set; }
        public string FinalEditCompleted { get; set; }
        public Nullable<System.DateTime> FinalSentDate { get; set; }
        public bool TranscriptStatus { get; set; }
        public string TranscriptNote { get; set; }
        public bool IsAudioFormat { get; set; }
        public bool IsVideoFormat { get; set; }
        public bool IsBornDigital { get; set; }
        public byte OriginalMediumType { get; set; }
        public string OriginalMedium { get; set; }
        public bool IsConvertToDigital { get; set; }
        public Nullable<System.DateTime> ConvertToDigitalDate { get; set; }
        public bool IsAccessMediaStatus { get; set; }
        public string TechnicalSpecification { get; set; }
        public string MasterFileLocation { get; set; }
        public string AccessFileLocation { get; set; }
        public string TranscriptLocation { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string InterviewerDescription { get; set; }
        public string InterviewerKeywords { get; set; }
        public string InterviewerSubjects { get; set; }
        public string EquipmentNumber { get; set; }
        public bool SentOut { get; set; }
        public string MetadataDraft { get; set; }
    }
}
